language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
  - rbx
matrix:
  allow_failures:
    - rvm: rbx
    - rvm: ruby-head
# HACK: Fix problems with native libraries on ruby-head
before_install:
  - gem install rugged -v 0.17.0.b7 -- --with-cflags='--std=gnu99'
  - gem install nokogiri redcarpet -- --with-cflags='--std=gnu99'
